### ISSUE TITLE
Non deterministic results

### ISSUE THREAD

**Issue by tantikristanti** [kermitt2/nerd#51] opened 2018-01-15 15:53 UTC
In order to test the process of disambiguation, some possibilities of query were given.
Let's take test cases with disambiguation of Pdf files, the service showed a strange behavior since it gave different results even for **the same query**. 
The following is some test cases done on a Pdf file with the same query template:
[2009.Infiniti.pdf](https://github.com/kermitt2/nerd/files/1632216/2009.Infiniti.pdf)

```
{
    "mentions": [
        "ner",
        "wikipedia"
    ],
    "nbest": false,
    "customisation": "generic"
}
```

The service gave different results, for instance the mention 'Francesco Speranza' can be full recognized as 'Francesco Speranza', can partially recognized as 'Speranza', or even cannot be recognized at all.

Below are some screenshots of the results.

1. 'Francesco Speranza' can be full recognized 
<img width="643" alt="screen shot 2018-01-15 at 16 41 10" src="https://user-images.githubusercontent.com/28044697/34950832-958d70ce-fa14-11e7-957d-83a0cfcdf793.png">

2. 'Francesco Speranza' can partially recognized as 'Speranza'
<img width="581" alt="screen shot 2018-01-15 at 16 51 44" src="https://user-images.githubusercontent.com/28044697/34950848-9f4c490a-fa14-11e7-95f5-5e77ff4b3266.png">

3. 'Francesco Speranza' cannot be recognized at all
<img width="670" alt="screen shot 2018-01-15 at 16 39 54" src="https://user-images.githubusercontent.com/28044697/34950821-88ebe968-fa14-11e7-8482-7cedd4267aa9.png">

**Comment by kermitt2** [comment] 2018-01-16 08:56
This is something visible for long. My hypothesis is that it is due to the random seed of SMILE, leading to different partitioning of decision trees in the ensemble decision algo, and thus different probabilities - above or bellow the thresholds, and finally to this non-deterministic behaviour. 
If it comes from that, in sklearn we typically fix the random seed for reproducibility.

**Comment by kermitt2** [comment] 2018-01-16 09:07
Also note that it has nothing specific to the PDF, it is apparent whatever input we provide to the monster :)

**Comment by lfoppiano** [comment] 2018-01-27 08:12
I found that the HAL_1 example on the stable version (0.0.2) is pretty fuzzy. `Himalaya` is sometimes recognised, sometimes not (tested in `huma-num/nerd`)

**Comment by lfoppiano** [comment] 2018-01-31 17:06
This query, on the other hand, show certain stability: 

```
{
    "text": "Solo un ricorso in Cassazione nelle prossime 48 ore può salvare le 15 candidature uninominali della coalizione di centrodestra nella circoscrizione Lombardia 1 alla Camera: l’ufficio elettorale della corte d’Appello di Milano le ha infatti escluse in conseguenza della mancanza della dichiarazione di apparentamento alla coalizione da parte della lista «Noi con l’Italia». I candidati in questione sono: Michela Vittoria Brambilla (nel collegio di Abbiategrasso) , Massimo Garavaglia (Legnano), Andrea Crippa (Bollate), Paola Frassinetti (Seregno), Andrea Mandelli (Monza), Valentina Aprea (Gorgonzola), Jari Colla (Cinisello Balsamo), Luca Squeri (Cologno Monzese), Guido Della Frera (Milano - Sesto), Alessandro Morelli (Milano), Igor Iezzi (Milano), Cristina Rossello (Milano), Laura Molteni (Milano), Federica Zanella (Milano) e Graziano Musella (Rozzano). I rappresentanti della lista sostengono che in realtà quel documento sarebbe stato depositato, come avvenuto in tutta Italia, dalla lista «capofila» (Forza Italia), che aveva presentato l’intera documentazione. ",
    "language": {
        "lang": "it"
    },
    "entities": [],
    "mentions": [
        "ner",
        "wikipedia"
    ],
    "nbest": false,
    "sentence": false,
    "customisation": "generic"
}
```

**Comment by lfoppiano** [comment] 2018-01-31 17:44
Here a quick and dirty way to make some preliminary tests - counting the number of entities returned: 
```
wifi-pro-82-244:tests lfoppiano$ for i in {1..10}; do curl --silent 'http://localhost:8090/service/disambiguate' -X POST -F "query={'language': {'lang':'it'}}, 'mentions': ['ner', 'wikipedia']}" -F"file=@2009Infiniti.pdf" | jq -r '.entities' | grep 'rawName' | wc -l; done;
     142
     125
     128
     142
     132
     133
     122
     125
     133
     136
wifi-pro-82-244:tests lfoppiano$ 
```

**Comment by lfoppiano** [comment] 2018-01-31 17:48
Here an example with text: 

```
wifi-pro-82-244:tests lfoppiano$ for i in {1..10}; do curl --silent 'http://nerd.huma-num.fr/test/service/disambiguate' -X POST -F 'query={
>   "text": "Treno fuori dai binari alla stazione di Roma-Termini: durante la manovra di trasferimento di un convoglio senza passeggeri verso il deposito, un carrello di un vagone è uscito dal binario. Il traffico ferroviario - ha reso noto Rfi sul portale d’informazioni - sta registrando dalle 10.30 di mercoledì 31, modifiche e rallentamenti fino a 30 minuti sulle linee Roma - Civitavecchia e Roma - Cassino. Sono in corso di accertamento le cause dell’episodio avvenuto intorno alle 10.30 e che ha provocato ritardi a catena su diverse linee regionali. \nPer l’anormalità tecnica in atto a Roma Termini - si legge - il traffico sulla linea Roma–Cassino registra ritardi medi di 30 minuti. Alcuni treni sulla linea Roma – Civitavecchia sono, invece, limitati nella stazione di Roma Ostiense. Per il servizio no-stop da Roma Termini a Fiumicino Aeroporto con il Leonardo Express, invece è stato riprogrammato con un treno ogni 30 minuti. I treni infatti non possono arrivare e partire dai binari 19, 20, 21. L’episodio del Frecciabianca a Roma, arriva a qualche giorno dalla tragedia avvenuta alle porte di Milano, dove un convoglio di Trenord è uscito dai binari durante la sua corsa, per andarsi a schiantare contro un palo. Terribile il bilancio delle vittime dell’incidente con tre donne morte e decine di feriti. \nTrenitalia fa sapere di aver potenziato l’assistenza ai passeggeri nelle stazioni di Ciampino, Ostiense e Termini: sono in corso le verifiche sul treno incidentato che dovrà essere rimesso in asse e poi spostato dal binario. Al momento i treni per Grosseto e Pisa partono da Termini con frequenze di un’ora; mentre il capolinea dei mezzi da Civitavecchia a Roma è stato spostato alla stazione Ostiense. I ritardi sulle linee, come ad esempio per Cassino, si attestano per ora intorno ai trenta minuti. Regolare il traffico ferroviario sulla tratta del Leonardo Express per Fiumicino.", "mentions": [ "ner", "wikipedia"]}' | jq -r '.entities' | grep 'rawName' | wc -l ; done;
      37
      37
      37
      37
      37
      37
      37
      37
      37
      37
wifi-pro-82-244:tests lfoppiano$ 
```

**Comment by lfoppiano** [comment] 2018-02-01 08:45
To be checked: https://github.com/haifengl/smile/issues/262

**Comment by kermitt2** [comment] 2018-02-12 14:31
ok so fixing the seed for smile ML do not solve the problem :(
let's further explore...

**Comment by kermitt2** [comment] 2018-02-15 15:42
The problem was coming from the way the context is built - the sort of entities preliminary to building a context was not deterministic, resulting in different selection of senses from one request to the other for the same input.

**Comment by kermitt2** [comment] 2018-02-15 17:28
Should be now entirely fixed with commit 79e4e98c53634d8dfafe59d729c17327ccb3bda8

**Comment by lfoppiano** [comment] 2018-02-15 18:12
Looks it's fixed: 
```
Johan:tests lfoppiano$ for i in {1..10}; do curl --silent 'http://localhost:8091/service/disambiguate' -X POST -F "query={'language': {'lang':'it'}}, 'mentions': ['ner', 'wikipedia']}" -F"file=@Bodria_Berruto.pdf" | jq -r '.entities' | grep 'rawName' | wc -l; done;
     822
     822
     822
     822
     822
     822
     822
     822
     822
     822
Johan:tests lfoppiano$ 
```
```Johan:tests lfoppiano$ for i in {1..10}; do curl --silent 'http://localhost:8091/service/disambiguate' -X POST -F "query={'language': {'lang':'it'}}, 'mentions': ['ner', 'wikipedia']}" -F"file=@2009Infiniti.pdf" | jq -r '.entities' | grep 'rawName' | wc -l; done;
     109
     109
     109
     109
     109
     109
     109
     109
     109
     109
Johan:tests lfoppiano$ 
```

**Comment by lfoppiano** [comment] 2018-02-15 18:15
Same example as https://github.com/kermitt2/nerd/issues/51#issuecomment-362013801
```
Johan:tests lfoppiano$ for i in {1..10}; do curl --silent 'http://localhost:8091/service/disambiguate' -X POST -F 'query={  "text": "Treno fuori dai binari alla stazione di Roma-Termini: durante la manovra di trasferimento di un convoglio senza passeggeri verso il deposito, un carrello di un vagone è uscito dal binario. Il traffico ferroviario - ha reso noto Rfi sul portale d’informazioni - sta registrando dalle 10.30 di mercoledì 31, modifiche e rallentamenti fino a 30 minuti sulle linee Roma - Civitavecchia e Roma - Cassino. Sono in corso di accertamento le cause dell’episodio avvenuto intorno alle 10.30 e che ha provocato ritardi a catena su diverse linee regionali. \nPer l’anormalità tecnica in atto a Roma Termini - si legge - il traffico sulla linea Roma–Cassino registra ritardi medi di 30 minuti. Alcuni treni sulla linea Roma – Civitavecchia sono, invece, limitati nella stazione di Roma Ostiense. Per il servizio no-stop da Roma Termini a Fiumicino Aeroporto con il Leonardo Express, invece è stato riprogrammato con un treno ogni 30 minuti. I treni infatti non possono arrivare e partire dai binari 19, 20, 21. L’episodio del Frecciabianca a Roma, arriva a qualche giorno dalla tragedia avvenuta alle porte di Milano, dove un convoglio di Trenord è uscito dai binari durante la sua corsa, per andarsi a schiantare contro un palo. Terribile il bilancio delle vittime dell’incidente con tre donne morte e decine di feriti. \nTrenitalia fa sapere di aver potenziato l’assistenza ai passeggeri nelle stazioni di Ciampino, Ostiense e Termini: sono in corso le verifiche sul treno incidentato che dovrà essere rimesso in asse e poi spostato dal binario. Al momento i treni per Grosseto e Pisa partono da Termini con frequenze di un’ora; mentre il capolinea dei mezzi da Civitavecchia a Roma è stato spostato alla stazione Ostiense. I ritardi sulle linee, come ad esempio per Cassino, si attestano per ora intorno ai trenta minuti. Regolare il traffico ferroviario sulla tratta del Leonardo Express per Fiumicino.", "mentions": [ "ner", "wikipedia"]}' | jq -r '.entities' | grep 'rawName' | wc -l ; done;
      44
      44
      44
      44
      44
      44
      44
      44
      44
      44
```

**Closed** 2018-02-19 12:28 UTC
Labels: bug
